### ISSUE TITLE
[Feature Request] Add support for br Content-Type.

### ISSUE THREAD

**Issue by zw963** [hmdne/roda-sprockets#11]
### The reason:

Roda's public plugin support serve brotli assets if those assets was exsits.

```
 # :brotli :: Whether to serve already brotli-compressed files with a .br extension
      #            for clients supporting brotli transfer encoding.
```

So, the only need is add options like this:

```rb
plugin :public, gzip: true, brotli: true
```

Then roda can serve as brotli if current connection is https.

so, i write a cap tasks for do this, it dirty, but works

```rb
desc "deflate assets use brotli"
  task :deflate do
    on roles(fetch(:procodile_roles, [:app])) do
      deploy_to = capture("cd #{deploy_to()}; pwd")
      assets_folder = "#{deploy_to}/shared/public/assets"
      within release_path do
        ruby_script = <<-HEREDOC
require "json"
require "brotli"
sprockets_manifest_json_file = Dir.glob("#{assets_folder}/.sprockets-manifest*.json").first
assets = JSON.load_file(sprockets_manifest_json_file).dig("assets").values
assets.each do |asset|
  asset_file = "#{assets_folder}/" + asset
  writer = Brotli::Writer.new File.open(asset_file +".br", "w")
  writer.write File.read(asset_file)
  writer.close
end
HEREDOC
        info "Creating brotli compressed assets"
        execute :bundle, "exec ruby -e '#{ruby_script}'"
      end
    end
  end
```

basically, i follow the example here https://github.com/miyucy/brotli/blob/master/test/brotli_writer_test.rb

following is response header when use Firefox.

![image](https://user-images.githubusercontent.com/549126/130331459-d90cbbcd-2eb2-48d7-b927-8a17556b01b0.png)

But, i consider this generate `app-???.js.br` process can be done when run `rake assets:precompile`, so, give this purpose. 

there need some [extra steps](https://github.com/miyucy/brotli/blob/master/test/brotli_writer_test.rb) if serve as nginx, e.g. enable https, add brotli module.

**Comment by hmdne** [comment]
This request should go to Sprockets upstream first, as it doesn't support Brotli right now

**Comment by hmdne** [comment]
NB: In my app I do this:

```ruby
task :brotli do
  Dir["public/assets/.sprockets-manifest*"].each do |mf|
    mfd = JSON.load(File.read(mf))
    mfd["assets"].values.each do |f|
      fn = File.dirname(mf) + "/" + f

      sh "brotli -Zfvw 0 #{fn}"
    end
  end
end

**Comment by zw963** [comment]
> This request should go to Sprockets upstream first, as it doesn't support Brotli right now

Yes, i know sprockets not support yet, but for us, we have non-zipped assets file generated after done assets precompile, if we can this file path, create br pre-zipped assets very easy.

```rb
  require 'brotli'

  asset_file = "/public/assets/app-?????.json"
  writer = Brotli::Writer.new File.open(asset_file +".br", "w")
  writer.write File.read(asset_file)
  writer.close
```

**Comment by zw963** [comment]
> NB: In my app I do this:

~~BTW, you will run this task from remote server environment manually after deploy done?
Or, run locally, and then upload those file to remote server?~~

~~AFAK, this task should not work if deploy with capistrano, because `Dir["public/assets/.sprockets-manifest*"]` run on local machine instead remote.~~

Never mind, i can create a rake task, and run this rake task within a cap task on remote server ...

**Comment by zw963** [comment]
And, i find out more document about this, please check:

https://github.com/hansottowirtz/sprockets-exporters_pack/wiki/How-to-enable-Brotli-with-Rails-and%C2%A0Nginx

https://github.com/rails/sprockets/pull/372

it's seem like sprockets support hooks for us add bri support, right?

**Comment by hmdne** [comment]
This should mostly work. For the first thing, you can either do:

```ruby
Sprockets.register_exporter %w(text/css application/javascript image/svg+xml), Sprockets::ExportersPack::BrotliExporter
```

or

```ruby
App.sprockets_options[:sprockets].register_exporter %w(text/css application/javascript image/svg+xml), Sprockets::ExportersPack::BrotliExporter
```

(Agreed this is not the best syntax)

**Comment by zw963** [comment]
I tested, only latter works.

```rb
desc "Precompile assets"
  task :precompile do
    require_relative '../../config/environment'
    require 'roda/plugins/sprockets_task'
    Roda::RodaPlugins::Sprockets::Task.define!(App)
    warn "Precompiling assets"
    App.sprockets_options[:sprockets].register_exporter %w(text/css application/javascript image/svg+xml), Sprockets::ExportersPack::BrotliExporter
    Rake::Task['assets:precompile'].invoke
  end
```

**Comment by zw963** [comment]
Anyway, this is not a necessary feature which need add to roda-sprockets, just a discuss, 

if we want, maybe we can port the code in `sprockets-exporters_pack` gem into here instead.

always generate br zipped asset is not a bad things anyway.

**Comment by hmdne** [comment]
I think this is not a scope of this project per se :D. It may be a good idea to integrate this directly into sprockets. Anyway, I found some places where `.gz` is hardcoded, like:

https://github.com/rails/sprockets/blob/master/lib/sprockets/manifest.rb#L217

Anyway the next commit will add `App.sprockets_env` shortcut, so you will be able to do just `    App.sprockets_env.register_exporter %w(text/css application/javascript image/svg+xml), Sprockets::ExportersPack::BrotliExporter`

And also we can document this part.
