### ISSUE TITLE
RACK_ENV=production rake assets:precompile task never skipped even file name digest and file content never changed.

### ISSUE THREAD

**Issue by zw963** [hmdne/roda-sprockets#5]
Following is a example

```sh
 ╰─ $  time RACK_ENV=production rake assets:precompile
DB connected: sqlite://db/files/marketbet_crawler_production.db

real    0m36.885s
user    0m41.275s
sys     0m0.774s

 ╭─ 14:49  zw963 ⮀ ~/Stocks/marketbet_crawler ⮀ ⭠ (c91077c) master $%  ➦ ruby-3.0.2@marketbet_crawler  0 
 ╰─ $ time RACK_ENV=production rake assets:precompile
DB connected: sqlite://db/files/marketbet_crawler_production.db

real    0m35.975s
user    0m40.153s
sys     0m0.774s
```

In fact, the second run generate same js file and digest as first run.
so, why not just skip it?

**Comment by hmdne** [comment]
This is a good question - happens in my application as well, but not in the test environment... Sprockets cache is a very difficult thing and I'm sure even opal-sprockets has something done wrong.

**Comment by hmdne** [comment]
My theory is that... you need to compile things before you are able to compute dependencies and later checksums

**Comment by zw963** [comment]
>  I'm sure even opal-sprockets has something done wrong.

: (



> you need to compile things before you are able to compute dependencies and later checksums

Yes, after some research, i have same thought, maybe there maybe somethings we don't know anyway.
