### ISSUE TITLE
rake assets:clean task is very very dangeous

### ISSUE THREAD

**Issue by zw963** [hmdne/roda-sprockets#6]
https://github.com/hmdne/roda-sprockets/blob/master/lib/roda/plugins/sprockets_task.rb#L19-L23

It should only delete files which create by rack assets:precompile.

**Comment by zw963** [comment]
If we should use the tasks provided by sprockets instead?

https://github.com/rails/sprockets/blob/master/lib/rake/sprocketstask.rb#L133

**Comment by hmdne** [comment]
I refactored this in terms of sprocketstask, but the thing is, `manifest.clobber` has exactly the same semantics while `manifest.clean` doesn't for example remove the current asset. We may think about changing the semantics here later though. I think that with #7 fixed we can also consider this one fixed.

**Comment by zw963** [comment]
Cool, i tested, when run `rake assets:clean`, manifest.colobber will delete `public/assets` folder instead.

that is, it consider this same behavior as before, right? though, because we are add a public/assets folder, that not take effect the others files(which maybe serve by nginx) in public folder anyway, e.g.  public/some_picture.png

**Comment by hmdne** [comment]
Exactly, that's the point. Giving "public" in documentation was clearly an omission on my part.
